// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/LimelightOff.h"
#include <iostream>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

LimelightOff::LimelightOff(): frc::Command() {
    // Use Requires() here to declare subsystem dependencies
    // eg. Requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::vision.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    SetRunWhenDisabled(true);
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void LimelightOff::Initialize() {

std::cout << "Limelight Off!" << std::endl;

Robot::vision->setCameraMode(0);
Robot::vision->setLedMode(1);
Robot::vision->setPipeline(1);

}

// Called repeatedly when this Command is scheduled to run
void LimelightOff::Execute() {

frc::SmartDashboard::PutNumber("Target Area", Robot::vision->getTa());
frc::SmartDashboard::PutNumber("Horizontal Offset", Robot::vision->getTx());

}

// Make this return true when this Command no longer needs to run execute()
bool LimelightOff::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void LimelightOff::End() {
Robot::vision->setLedMode(3);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LimelightOff::Interrupted() {
End();
}
